name: deploy bitou.tech to server

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    # 定义job运行环境，使用linux环境
    runs-on: ubuntu-latest
    steps:
      # 对应第2步，借助已有脚本拉取代码
      - name: Checkout
        uses: actions/checkout@master

      # 第3步的准备工作，先配置好node环境
      - uses: actions/setup-node@v2
        with:
          node-version: "21"

      # 对应第3步，执行打包命令
      - name: "Build"
        run: |
          npm install
          npm run build

      # 对应第4、5步，配置参数登陆服务器+拷贝到指定目录
      - name: Upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          # 拷贝 .next、public文件夹和package.json文件到服务器指定目录
          source: ".next/,public/,package.json"
          target: "/root/codezone/bitou-nextjs"

      # 对应第6步，重启安装依赖、后端服务2
      - name: Server Reload
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /root/codezone/bitou-nextjs
            npm install
            pm2 restart bitou-website
